<form method="post" action="index.php" enctype="multipart/form-data">
			<p>
				<label>Nome atividade</label>
				<input  type="name" name="nome" id="name" />
			</p>
			<p>
				<label>Link:</label>
				<input  type="text" name="link" id="link"/>
			</p>
			<p>
				<label>Data:</label>
				<input type="date" name="data" id="data"/>
			</p>
			<p>
				<label>Arquivo:</label>
				<input type="file" name="arquivo" id="arquivo"/>
			</p>
			<p>
				<input type="submit" value="Enviar"/>
			</p>
</form>